"""create_consultas_servicios_procedimientos_table

Revision ID: 18359e78517f
Revises: 32d8b9a8eee3
Create Date: 2026-08-19 17:45:33.054655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '18359e78517f'
down_revision: Union[str, Sequence[str], None] = '32d8b9a8eee3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rips',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('num_documento_id_obligatorio', sa.String(length=12), nullable=False, comment='Numero NIT con el cual se indetifique el facturador electronico'),
    sa.Column('num_factura', sa.String(length=20), nullable=False, comment='Numero de factura'),
    sa.Column('tipo_nota', sa.String(length=2), nullable=True, comment='tipo nota'),
    sa.Column('num_nota', sa.String(length=20), nullable=True, comment='numero de nota'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rips_servicios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rips_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rips_id'], ['rips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rips_usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rips_id', sa.Integer(), nullable=False),
    sa.Column('tipo_documento_identificacion', sa.String(length=2), nullable=False, comment='Nombre del usuario'),
    sa.Column('num_documento_identificacion', sa.String(length=12), nullable=False, comment='Numero de documento del usuario'),
    sa.Column('tipo_usuario', sa.String(length=2), nullable=False, comment='Tipo de usuario'),
    sa.Column('fecha_nacimiento', sa.DateTime(timezone=True), nullable=False, comment='Fecha Nacimiento del usuario'),
    sa.Column('cod_sexo', sa.String(length=1), nullable=False, comment='Sexo del usuario'),
    sa.Column('cod_pais_residencia', sa.String(length=3), nullable=False, comment='Codigo pais de origen del usuario'),
    sa.Column('cod_pais_origen', sa.String(length=3), nullable=False, comment='Codigo pais de origen del usuario'),
    sa.Column('cod_municipio_residencia', sa.String(length=5), nullable=False, comment='Codigo muncipio de residencia del usuario'),
    sa.Column('cod_zona_territorial_residencia', sa.String(length=2), nullable=False, comment='Codigo zona territorial de residencia del usuario'),
    sa.Column('incapacidad', sa.String(length=2), nullable=False, comment='Incapcacidad del usuario'),
    sa.Column('registroSIRAS', sa.String(length=20), nullable=False, comment='Registro SIRAS del usuario'),
    sa.Column('consecutivo', sa.Integer(), nullable=False, comment='Consecutivo del usuario'),
    sa.ForeignKeyConstraint(['rips_id'], ['rips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rips_consultas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('servicios_id', sa.Integer(), nullable=True),
    sa.Column('cod_prestador', sa.String(length=12), nullable=False, comment='Codigo del prestador'),
    sa.Column('fecha_inicio_atencion', sa.DateTime(timezone=True), nullable=False, comment='Fecha de inicio de atencion'),
    sa.Column('num_authorizacion', sa.String(length=30), nullable=True, comment='Numero de autorizacion'),
    sa.Column('cod_consulta', sa.String(length=6), nullable=False, comment='Codigo de la consulta'),
    sa.Column('modalidad_grupo_servicio_tec_sal', sa.String(length=2), nullable=False, comment='Determina la forma de prestar un servicio de salud en condiciones particulares en relacion con el grupo de servicios'),
    sa.Column('grupo_servicios', sa.String(length=2), nullable=False, comment='Representa la agrupacion de servicios que se encuentran relacionados con un procedimiento de salud'),
    sa.Column('cod_servicio', sa.Integer(), nullable=False, comment='Codigo de servicio'),
    sa.Column('finalidad_tec_salud', sa.String(length=2), nullable=False, comment='Identificador de la finalidad con la que se realiza un procedimiento'),
    sa.Column('causa_motivo_atencion', sa.String(length=2), nullable=False, comment='Identificador de la causa o motivo de atencion'),
    sa.Column('cod_diagnostico_principal', sa.String(length=4), nullable=False, comment='Codigo del diagnosttico principal (CIE-10)'),
    sa.Column('cod_diagnostico_principal_cie11', sa.String(length=255), nullable=True, comment='Codigo del diagnostico principal (CIE-11)'),
    sa.Column('nom_cod_diagnostico_principal_cie11', sa.Text(), nullable=True, comment='Nombre correspondiente al diagnostico principal cie11'),
    sa.Column('cod_diagnostico_relacionado1', sa.String(length=4), nullable=True, comment='Codigo del diagnostico relacionado 1 (CIE-10)'),
    sa.Column('cod_diagnostico_relacionado1_cie11', sa.String(length=255), nullable=True, comment='Codigo del diagnostico relacionado 1 (CIE-11)'),
    sa.Column('nom_cod_diagnostico_relacionado1_cie11', sa.String(length=255), nullable=True, comment='Nombre correspondiente al diagnostico relacionado 1 cie11'),
    sa.Column('cod_diagnostico_relacionado2', sa.String(length=4), nullable=True, comment='Codigo del diagnostico relacionado 2 (CIE-10)'),
    sa.Column('cod_diagnostico_relacionado2_cie11', sa.String(length=255), nullable=True, comment='Codigo del diagnostico relacionado 2 (CIE-11)'),
    sa.Column('nom_cod_diagnostico_relacionado2_cie11', sa.String(length=255), nullable=True, comment='Nombre correspondiente al diagnostico relacionado 2 cie11'),
    sa.Column('cod_diagnostico_relacionado3', sa.String(length=4), nullable=True, comment='Codigo del diagnostico relacionado 2 (CIE-10)'),
    sa.Column('cod_diagnostico_relacionado3_cie11', sa.String(length=255), nullable=True, comment='Codigo del diagnostico relacionado 2 (CIE-11)'),
    sa.Column('nom_cod_diagnostico_relacionado3_cie11', sa.String(length=255), nullable=True, comment='Nombre correspondiente al diagnostico relacionado 2 cie11'),
    sa.Column('tipo_diagnostico_principal', sa.String(length=2), nullable=False, comment='Identificador del tipo de diagnostico principal'),
    sa.Column('tipo_documento_identificacion', sa.String(length=2), nullable=False, comment='Tipo de documento de indentificacion del profesional que ordeno o realizo el procedimiento'),
    sa.Column('num_documenento_identificacion', sa.String(length=20), nullable=False, comment='Numero de documento de indentificacion del profesional que ordeno o realizo el procedimiento'),
    sa.Column('valor_servicio', sa.Integer(), nullable=False, comment='Valor del servicio'),
    sa.Column('concepto_recaudo', sa.String(length=2), nullable=False, comment='Concepto de recaudo'),
    sa.Column('valor_pago_moderador', sa.Integer(), nullable=False, comment='Valor del pago moderador'),
    sa.Column('num_fev_pago_moderador', sa.String(length=30), nullable=True, comment='Numero de FEV del pago moderador'),
    sa.Column('codigo_vida', sa.String(length=50), nullable=True, comment='Codigo de vida'),
    sa.Column('consecutivo', sa.Integer(), nullable=False, comment='Consecutivo del procedimiento'),
    sa.ForeignKeyConstraint(['servicios_id'], ['rips_servicios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rips_consultas_servicios_id'), 'rips_consultas', ['servicios_id'], unique=False)
    op.create_table('rips_procedimientos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cod_prestador', sa.String(length=20), nullable=False, comment='Codigo del prestador'),
    sa.Column('servicios_id', sa.Integer(), nullable=True),
    sa.Column('fecha_inicio_atencion', sa.DateTime(timezone=True), nullable=False, comment='Fecha de inicio de atencion'),
    sa.Column('id_mipres', sa.String(length=30), nullable=True, comment='Id mipres'),
    sa.Column('num_autorizacion', sa.String(length=30), nullable=True, comment='Numero de autorizacion'),
    sa.Column('cod_procedimiento', sa.String(length=10), nullable=False, comment='Codigo del procedimiento'),
    sa.Column('via_ingreso_servicio_salud', sa.String(length=2), nullable=False, comment='Via de ingreso del servicio de salud'),
    sa.Column('madalidad_grupo_servicio_tec_sal', sa.String(length=2), nullable=False, comment='Determina la forma de prestar un servicio de salud en codiciones particulares en relacion con el grupo de servicios'),
    sa.Column('grupo_servicios', sa.String(length=2), nullable=False, comment='Representa la agrupacion de servcios que se encuentran relacionados con un procedimiento de salud'),
    sa.Column('cod_servicio', sa.Integer(), nullable=False, comment='Codigo de servicio'),
    sa.Column('finalidad_tec_salud', sa.String(length=2), nullable=False, comment='Identificador de la finalidad con la que se realiza un procedidmiento'),
    sa.Column('tipo_documento_identificacion', sa.String(length=2), nullable=False, comment='Tipo de documento de indentificacion del profesional que ordeno o realizo el procedimiento'),
    sa.Column('num_documenento_identificacion', sa.String(length=20), nullable=False, comment='Numero de documento de indentificacion del profesional que ordeno o realizo el procedimiento'),
    sa.Column('cod_diagnostico_principal', sa.String(length=10), nullable=False, comment='Codigo del diagnostico principal (CIE-10)'),
    sa.Column('cod_diagnostico_principal_cie11', sa.String(length=255), nullable=True, comment='Codigo del diagnostico principal (CIE-11)'),
    sa.Column('nom_cod_diganostico_principal_cie11', sa.Text(), nullable=True, comment='Nombre correspondiente al diagnostico principal cie11'),
    sa.Column('cod_diagnostico_relacionado', sa.String(length=4), nullable=True, comment='Codigo del diagnostico relacionado (CIE-10)'),
    sa.Column('cod_diagnostico_relacionado_cie11', sa.String(length=255), nullable=True, comment='Codigo del diagnostico relacionado (CIE-11)'),
    sa.Column('nom_cod_diagnostico_relacionado_cie11', sa.Text(), nullable=True, comment='Nombre correspondiente al diagnostico relacionado cie11'),
    sa.Column('cod_complicacion', sa.String(length=4), nullable=True, comment='Codigo del diagnostico de complicacion (CIE-10)'),
    sa.Column('cod_complicacion_cie11', sa.Text(), nullable=True, comment='Codigo del diagnostico de complicacion (CIE-11)'),
    sa.Column('nom_cod_complicacion_cie11', sa.Text(), nullable=True, comment='Nombre correspondiente al diagnostico de complicacion cie11'),
    sa.Column('vr_servicio', sa.Integer(), nullable=False, comment='Valor del servicio'),
    sa.Column('concepto_recaudo', sa.String(length=2), nullable=False, comment='Concepto de recaudo'),
    sa.Column('valor_pago_moderador', sa.Integer(), nullable=False, comment='Valor del pago moderador'),
    sa.Column('num_fev_pago_moderador', sa.String(length=30), nullable=True, comment='Numero de FEV del pago moderador'),
    sa.Column('codigo_vida', sa.String(length=50), nullable=True, comment='Codigo de vida'),
    sa.Column('consecutivo', sa.Integer(), nullable=False, comment='Consecutivo del procedimiento'),
    sa.ForeignKeyConstraint(['servicios_id'], ['rips_servicios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rips_procedimientos_servicios_id'), 'rips_procedimientos', ['servicios_id'], unique=False)
    op.alter_column('rips_old', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('rips_old', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rips_old', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('rips_old', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_rips_procedimientos_servicios_id'), table_name='rips_procedimientos')
    op.drop_table('rips_procedimientos')
    op.drop_index(op.f('ix_rips_consultas_servicios_id'), table_name='rips_consultas')
    op.drop_table('rips_consultas')
    op.drop_table('rips_usuarios')
    op.drop_table('rips_servicios')
    op.drop_table('rips')
    # ### end Alembic commands ###
