"""fix fk orders batch_id

Revision ID: 48d298c3b0aa
Revises: 62bdbcc9e75d
Create Date: 2026-06-28 15:19:34.978104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '48d298c3b0aa'
down_revision: Union[str, Sequence[str], None] = '62bdbcc9e75d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_batches')
    op.drop_table('orders')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fecha', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('id_profesional', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('profesional', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('no_orden', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('codigo', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('procedimiento', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('cantidad', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dosis', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('dias_tto', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['order_batches.id'], name=op.f('orders_batch_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('orders_pkey'))
    )
    op.create_table('order_batches',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('uploaded_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('order_batches_uploaded_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('order_batches_pkey'))
    )
    # ### end Alembic commands ###
